CREATE EXTENSION IF NOT EXISTS pgcrypto;
DROP EXTENSION IF EXISTS pgcrypto CASCADE;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
DROP EXTENSION IF EXISTS pg_trgm CASCADE;
CREATE EXTENSION fuzzystrmatch;
DROP EXTENSION IF EXISTS fuzzystrmatch CASCADE;